### ISSUE TITLE
Document that constructor injection _does_ work

### ISSUE THREAD

**Issue by bannmann** [shillner/maven-cdi-plugin-utils#28]
~~It seems that constructor-based injection does not work for processing steps: I got "no processing step class found" until I switched to field-based injection.~~

~~Please document this fact on the [Processing Steps](https://github.com/shillner/maven-cdi-plugin-utils/wiki/Processing-Steps) wiki page.~~

EDIT: I made a mistake, constructor injection _does_ work. Still, as the examples all use field-based injection, it may be helpful to document that constructor-based injection also works. I would have discovered my unrelated mistake earlier ;-)

**Comment by shillner** [comment]
Hi, first of all thank you for your contribution!

I've double checked that constructor injection works as expected and will document this asap.
I've also seen the bunch of issues and merge request regarding the logging stuff and will also try to check them and adapt the plugin asap.

There's unfortunately not so much time left because of my current projects. But I'll try ;)
